### ISSUE TITLE
Error con versión de Java

### ISSUE THREAD

**Issue by Dviela** [Dviela/Readify#2]
Al iniciar la aplicación aparece un error con la versión de JDK:
![versionJavaIDE](https://github.com/Dviela/Readify/assets/99658403/82b996c8-2fe9-467c-9df6-60b3c6119ebe)

**Comment by EJLT** [comment]
Para solucionar este error hay que actualizar Java a una versión 20 o superior o hacer el proyecto en una versión inferior.
